# Absentieesm data
Problem statement:

In [2]:
#importig libraries 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
#Loading the data
df=pd.read_csv("Absenteeism_data.csv")

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


In [5]:
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [12]:
#since 'ID' is nominal data and may effect the precision of the result it is better to drop
df=df.drop(['ID'],axis=1)
df.head()

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [14]:
#Dealing with Categorical data
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [15]:
len(df['Reason for Absence'].unique())

28

In [17]:
#getting dummy variables for categorical data
reasons=pd.get_dummies(df['Reason for Absence'])
reasons

0   1   2   3   4   5   6   7   8   9   ...  18  19  21  22  23  24  25  \
0     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1     1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
3     0   0   0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   
4     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
695   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
696   0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
697   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
698   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
699   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

     26  27  28  
0     1   0   0  
1     0   0   0  
2     0   0   0  
3     0   0   0  
4     0   0   0  
..   ..  ..  ..  
695   0   0   0  
696   0   0   0  
697   0   0   0  
698   0   0   0  
699   0   0   1  

[700 rows x 28 columns]

In [18]:
#exploring categorical values
reasons['check']=reasons.sum(axis=1)
reasons

0  1  2  3  4  5  6  7  8  9  ...  19  21  22  23  24  25  26  27  28  \
0    0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   1   0   0   
1    1  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
2    0  0  0  0  0  0  0  0  0  0  ...   0   0   0   1   0   0   0   0   0   
3    0  0  0  0  0  0  0  1  0  0  ...   0   0   0   0   0   0   0   0   0   
4    0  0  0  0  0  0  0  0  0  0  ...   0   0   0   1   0   0   0   0   0   
..  .. .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
695  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
696  0  0  0  0  0  0  1  0  0  0  ...   0   0   0   0   0   0   0   0   0   
697  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
698  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   1   0   0   0   0   0   
699  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1   

     check  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
695      1  
696      1  
697      1  
698      1  
699      1  

[700 rows x 29 columns]

In [19]:
reasons['check'].unique()

array([1], dtype=int64)

In [22]:
reasons=reasons.drop(['check'], axis=1)

In [24]:
reasons=pd.get_dummies(df['Reason for Absence'],drop_first=True)
reasons

1   2   3   4   5   6   7   8   9   10  ...  18  19  21  22  23  24  25  \
0     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
3     0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
4     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
695   0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
696   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
697   0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
698   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
699   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

     26  27  28  
0     1   0   0  
1     0   0   0  
2     0   0   0  
3     0   0   0  
4     0   0   0  
..   ..  ..  ..  
695   0   0   0  
696   0   0   0  
697   0   0   0  
698   0   0   0  
699   0   0   1  

[700 rows x 27 columns]

In [25]:
#since adding all the columns will increase complexity grouping the reasons
#From the data description the reasons mentions are of different types
#Reasons 1 to 14 are diffrent types of diseases 
reason1=reasons.loc[:,1:14].max(axis=1) 
#15 to 17 related to pregnancy 
reason2=reasons.loc[:,15:17].max(axis=1) 
#18 to 21 signs not categoriesed 
reason3=reasons.loc[:,18:21].max(axis=1) 
#22 to 28 are light reasons
reason4=reasons.loc[:,22:28].max(axis=1) 

In [27]:
#dropping 'Reasons for Absence'
df=df.drop(['Reason for Absence'],axis=1)

In [28]:
df=pd.concat([df,reason1,reason2,reason3,reason4],axis=1)
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0  
2                          2  0  0  0  1  
3                          4  1  0  0  0  
4                          2  0  0  0  1

In [29]:
#renaming the columns
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [30]:
column_names=['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'reason1', 'reason2', 'reason3', 'reason4']
df.columns=column_names
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  reason1  reason2  reason3  reason4  
0                          4        0        0        0        1  
1                          0        0        0        0        0  
2                          2        0        0        0        1  
3                          4        1        0        0        0  
4                          2        0        0        0        1

In [31]:
df['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [32]:
type(df['Date'])

pandas.core.series.Series

In [34]:
df=df.drop('Date',axis=1)

In [58]:
df1=df.copy()

In [68]:
columns_reordered=['reason1', 'reason2', 'reason3', 'reason4','Education','Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets', 'Absenteeism Time in Hours',]
df1=df1[columns_reordered]
df1.head()

reason1  reason2  reason3  reason4  Education  Transportation Expense  \
0        0        0        0        1          1                     289   
1        0        0        0        0          1                     118   
2        0        0        0        1          1                     179   
3        1        0        0        0          1                     279   
4        0        0        0        1          1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Children  \
0                36   33                  239.554               30         2   
1                13   50                  239.554               31         1   
2                51   38                  239.554               31         0   
3                 5   39                  239.554               24         2   
4                36   33                  239.554               30         2   

   Pets  Absenteeism Time in Hours  
0     1                          4  
1     0                          0  
2     0                          2  
3     0                          4  
4     1                          2

In [104]:
df1['Absenteeism Time in Hours'].median()

3.0

In [105]:
df1['Absenteeism Time in Hours']=np.where(df1['Absenteeism Time in Hours']>df1['Absenteeism Time in Hours'].median(),1,0)

In [106]:
x=df1.iloc[:,0:12].values
y=df1.iloc[:,12].values
y

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [107]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)


In [108]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size = 0.8,)

In [109]:
X_train.shape
y_train.shape

(560,)

In [110]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=1000)
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [111]:
from sklearn import metrics
classifier.score(X_train, y_train)

0.7821428571428571

In [114]:
classifier.coef_

array([[ 2.0776309 ,  0.22958566,  1.49031534,  1.41331083, -0.11503412,
         0.67730708, -0.08305142, -0.24439243, -0.01667504,  0.34797938,
         0.51046279, -0.37998502]])